name: nearby_connections
description: Plugin for the android NearbyConnections API. Currently sending bytes (Uint8List) is possible. 
version: 0.1.3
author: Prerak Mann <mannprerak2@gmail.com>
homepage: https://github.com/mannprerak2/nearby_connections

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.pkmnapps.nearby_connections
    pluginClass: NearbyConnectionsPlugin
